(define-package "frontside-editing" "1.0.0" "Enhanced out of the box experience for text editing"
  '((yasnippet "0.11.0")
    (drag-stuff "0.3.0")
    (multiple-cursors "1.4.0")
    (which-key "2.0.1")
    (flycheck "31")
    (volatile-highlights "1.11")
    (undo-tree "0.7.5")
    (smartparens "1.11")
    (editorconfig "0.8.1")
    (emacs "26.1")))
